export type ViewKey =
  | 'dashboard'
  | 'aiPlan'
  | 'payday'
  | 'pots'
  | 'savingsInvestments'
  | 'spending'
  | 'allocatingPayments'
  | 'debts'
  | 'recurring'
  | 'calendar'
  | 'history'
  | 'settings'
